mywork/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [  
    url(r'^admin/', admin.site.urls),
    url(r'^timetable/', include('timetable.urls')),
]

timetable/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	# /timetable/
	url(r'^$', views.current, name='current'),

	# /timetable/addevent

	url(r'^addevent/(?P<indiv_slot_id>[0-9]+)$', views.addevent, name='addevent'),

	#/timetable/addevent/1212/thanks

	url(r'^addevent/(?P<indiv_slot_id>[0-9]+)/thanks$', views.thanks, name='thanks'),


]

timetable/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Slot(models.Model):
		
		day = models.CharField(max_length=50)
		time = models.BigIntegerField	()
		is_free = models.BooleanField(default=True)	

		def __str__(self):
			return self.day	+ '-' + str(self.time)	


class Event(models.Model):
		slot = models.ForeignKey(Slot, on_delete=models.CASCADE, null=True)
		ename = models.CharField(max_length=250)
		venue = models.CharField(max_length=500)
		code = models.BigIntegerField()

		def __str__(self):
			return self.ename






			

timetable/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from timetable.models import Event, Slot
# Create your views here.

def current(request):
	
	all_events = Event.objects.all()
	num_range = range(8,17)
	all_slots = Slot.objects.all()
	print num_range
	context = {
		'all_events' : all_events,
		'num_range' : num_range, 
		'all_slots': all_slots,
	}	
	


	return render(request, 'timetable/current.html', context)

def addevent(request,indiv_slot_id):
	
	selected_slot = Slot.objects.get(pk=indiv_slot_id)
	

	context ={
		'selected_slot': selected_slot,
		

	}

	return render(request, 'timetable/addevent.html',context)

def thanks(request,indiv_slot_id):

	selected_event =Event()
	selected_event.ename = request.POST['ename']
	selected_event.venue = request.POST['venue']
	selected_event.code = request.POST['code']
	
	

	selected_slot = Slot.objects.get(pk=indiv_slot_id)
	selected_event.slot = selected_slot
	selected_event.save()
	selected_slot.is_free = False
	
	selected_slot.save()

	return	render(request, 'timetable/thanks.html')

timetable/templates/timetable/addevent.html
<h1>ADD EVENT</h1>
<h3>{{ selected_slot }}</h3>


<form action="/timetable/addevent/{{ selected_slot.id }}/thanks" method="POST">

{% csrf_token %}

<p>
	<label for="(( selected_slot.id }}"> EVENT NAME: </label>
	
		<input type="text" name='ename' id="(( selected_slot.id }}" value="{{ selected_event.ename }}" />
		<br><br>
	<label for="(( selected_slot.id }}"> VENUE: </label>	
		<input type="text" name='venue' id="(( selected_slot.id }}" value="{{ selected_event.venue }}" />
		<br><br>

	<label for="(( selected_slot.id }}"> CODE: </label>
		<input type="number" name='code' id="(( selected_slot.id }}" value="{{ selected_event.code }}" />

		<br><br>
	<input type="submit" value="SUBMIT"/>

</p>
</form>

timetable/templates/timetable/current.html
<h1>This is Current timetable</h1>
<br>
<br>
<style>
table, th, td {
	border: 1px solid black;
	border-collapse: collapse;
}
th, td {
		padding: 5px;
}
</style>
<table style="width:60%">
	<tr>
		<th><h2><font color="Red">TIME/<br>DAY</font></h2></th>
		<th>8-9</th>
		<th>9-10</th>
		<th>10-11</th>
		<th>11-12</th>
		<th>12-1</th>
		<th>1-2</th>
		<th>2-3</th>
		<th>3-4</th>
		<th>4-5</th>
	</tr>
	<tr>
		<th>MONDAY</th>
		{% for indiv_slot in all_slots %}

			{% if indiv_slot.day == "MONDAY" %}
			<!-- HOW TO REMOVE HARDCODE HERE -->
			<form action= "addevent/{{ indiv_slot.id }}" method="POST">
			{% csrf_token %}	
						<td >	
						{% if indiv_slot.is_free %}
						<input type='radio' id="indiv_slot{{ forloop.counter }}" name='indiv_slot' value="{{ indiv_slot.id }}"/>
							<label for="indiv_slot{{ forloop.counter }}">
								FREE
							</label>
							<input type="submit" value="ADD EVENT"/>
						{% else %}
							{{ indiv_slot.event_set.all.0 }}
						</td>
						{% endif %}

			</form>	
			{% endif %}		
		{% endfor %}

	</tr>	
	<tr>	
		<th>TUESDAY</th>
		{% for indiv_slot in all_slots %}

			{% if indiv_slot.day == "TUESDAY" %}
			<!-- HOW TO REMOVE HARDCODE  URL 	HERE -->
			<form action= "addevent/{{ indiv_slot.id }}" method="POST">
			{% csrf_token %}	
						<td>	
						
						{% if indiv_slot.is_free %}
						<input type='radio' id="indiv_slot{{ forloop.counter }}" name='indiv_slot' value="{{ indiv_slot.id }}"/>
							<label for="indiv_slot{{ forloop.counter }}">
								FREE
							</label>
							<input type="submit" value="ADD EVENT"/>
						{% else %}
							{{ indiv_slot.event_set.all.0 }}
						</td>
						{% endif %}

			</form>	
			{% endif %}		
		{% endfor %}
	</tr>
	<tr>	
		<th>WEDNESDAY</th>
		{% for indiv_slot in all_slots %}

			{% if indiv_slot.day == "WEDNESDAY" %}
			<!-- HOW TO REMOVE HARDCODE HERE -->
			<form action= "addevent/{{ indiv_slot.id }}" method="POST">
			{% csrf_token %}	
						<td>	
						
						{% if indiv_slot.is_free %}
						<input type='radio' id="indiv_slot{{ forloop.counter }}" name='indiv_slot' value="{{ indiv_slot.id }}"/>
							<label for="indiv_slot{{ forloop.counter }}">
								FREE
							</label>
							<input type="submit" value="ADD EVENT"/>
						{% else %}
							{{ indiv_slot.event_set.all.0 }}
						</td>
						{% endif %}

			</form>	
			{% endif %}		
		{% endfor %}
	</tr>
	<tr>	
		<th>THURSDAY</th>
		{% for indiv_slot in all_slots %}

			{% if indiv_slot.day == "THURSDAY" %}
			<!-- HOW TO REMOVE HARDCODE HERE -->
			<form action= "addevent/{{ indiv_slot.id }}" method="POST">
			{% csrf_token %}	
						<td>	
						
						{% if indiv_slot.is_free %}
						<input type='radio' id="indiv_slot{{ forloop.counter }}" name='indiv_slot' value="{{ indiv_slot.id }}"/>
							<label for="indiv_slot{{ forloop.counter }}">
								FREE
							</label>
							<input type="submit" value="ADD EVENT"/>
						{% else %}
							{{ indiv_slot.event_set.all.0 }}
						</td>
						{% endif %}

			</form>	
			{% endif %}		
		{% endfor %}
	</tr>
	<tr>
		<th>FRIDAY</th>
		{% for indiv_slot in all_slots %}

			{% if indiv_slot.day == "FRIDAY" %}
			<!-- HOW TO REMOVE HARDCODE HERE -->
			<form action= "addevent/{{ indiv_slot.id }}" method="POST">
			{% csrf_token %}	
						<td>	
						
						{% if indiv_slot.is_free %}
						<input type='radio' id="indiv_slot{{ forloop.counter }}" name='indiv_slot' value="{{ indiv_slot.id }}"/>
							<label for="indiv_slot{{ forloop.counter }}">
								FREE
							</label>
							<input type="submit" value="ADD EVENT"/>
						{% else %}
							{{ indiv_slot.event_set.all.0 }}
						</td>
						{% endif %}

			</form>	
			{% endif %}		
		{% endfor %}
	</tr>
	<tr>
		<th>SATURDAY</th>
		{% for indiv_slot in all_slots %}

			{% if indiv_slot.day == "SATURDAY" %}
			<!-- HOW TO REMOVE HARDCODE HERE -->
			<form action= "addevent/{{ indiv_slot.id }}" method="POST">
			{% csrf_token %}	
						<td>	
						
						{% if indiv_slot.is_free %}
						<input type='radio' id="indiv_slot{{ forloop.counter }}" name='indiv_slot' value="{{ indiv_slot.id }}"/>
							<label for="indiv_slot{{ forloop.counter }}">
								FREE
							</label>
							<input type="submit" value="ADD EVENT"/>
						{% else %}
							{{ indiv_slot.event_set.all.0 }}
						</td>
						{% endif %}

			</form>	
			{% endif %}		
		{% endfor %}
	</tr>

</table>

timetable/templates/timetable/thanks.html
<h1>THANK YOU!</h1>